FileVersion = 1

[Project]
Name = "cmark-beef"
DefaultNamespace = "cmark"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\debug\\cmark.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\release\\cmark.lib"]