FileVersion = 1

[Project]
Name = "cmark-beef"
DefaultNamespace = "cmark"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\cmark_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\cmark.lib"]
